name: Salon application CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    working-directory: salon_manager

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Django test command
      run: |
        python manage.py test
    - name: Run Bandit
      run: |
        bandit -c pyproject.toml -r .
    - name: Run Safety
      run: |
        safety check
      continue-on-error: true
    - name: Run Ruff
      run: |
        ruff check
